### ISSUE TITLE
Target with the name "check" cannot be found in the VectorDrawable to be animated

### ISSUE THREAD

**Issue by Shahriyar13** [cortinico/slidetoact#48]
force close when complete animate in android 8.1.0 (27)

 java.lang.IllegalStateException: Target with the name "check" cannot be found in the VectorDrawable to be animated.
        at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.prepareLocalAnimator(AnimatedVectorDrawable.java:839)
        at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.prepareLocalAnimators(AnimatedVectorDrawable.java:817)
        at android.graphics.drawable.AnimatedVectorDrawable.ensureAnimatorSet(AnimatedVectorDrawable.java:930)
        at android.graphics.drawable.AnimatedVectorDrawable.start(AnimatedVectorDrawable.java:914)
        at com.ncorti.slidetoact.SlideToActView.startTickAnimation(SlideToActView.kt:611)
        at com.ncorti.slidetoact.SlideToActView.access$startTickAnimation(SlideToActView.kt:38)
        at com.ncorti.slidetoact.SlideToActView$startAnimationComplete$5.onAnimationUpdate(SlideToActView.kt:473)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1522)
        at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:654)
        at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:617)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1046)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1065)
        at android.animation.ValueAnimator.startWithoutPulsing(ValueAnimator.java:1058)
        at android.animation.AnimatorSet.handleAnimationEvents(AnimatorSet.java:1142)
        at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1046)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.-wrap2(Unknown Source:0)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

can i change complete icon?

**Comment by cortinico** [comment]
@Shahriyar13 Can you provide some steps on how to reproduce?

**Comment by cortinico** [comment]
Ideally this should be fixed with #73 
Feel free to reopen if is still crashing on `0.7.0`

**Comment by Akkiii** [comment]
`java.lang.IllegalStateException: Target with the name "check" cannot be found in the VectorDrawable to be animated.
        at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.prepareLocalAnimator(AnimatedVectorDrawable.java:848)
        at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.prepareLocalAnimators(AnimatedVectorDrawable.java:826)
        at android.graphics.drawable.AnimatedVectorDrawable.ensureAnimatorSet(AnimatedVectorDrawable.java:939)
        at android.graphics.drawable.AnimatedVectorDrawable.start(AnimatedVectorDrawable.java:923)
        at com.ncorti.slidetoact.SlideToActView.startTickAnimation(SlideToActView.kt:718)
        at com.ncorti.slidetoact.SlideToActView.access$startTickAnimation(SlideToActView.kt:36)
        at com.ncorti.slidetoact.SlideToActView$startAnimationComplete$5.onAnimationUpdate(SlideToActView.kt:567)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1558)
        at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:684)
        at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:647)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1079)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1098)
        at android.animation.ValueAnimator.startWithoutPulsing(ValueAnimator.java:1091)
        at android.animation.AnimatorSet.handleAnimationEvents(AnimatorSet.java:1149)
        at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1053)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1152)
        at android.view.Choreographer.doCallbacks(Choreographer.java:977)
        at android.view.Choreographer.doFrame(Choreographer.java:885)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1139)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

I am facing same issue. can you please help me?
I am using 0.7.0

**Comment by cortinico** [comment]
@Akkiii this is a old issue. Can you create a new one? Moreover, more details are needed. Ideally you should link to your project or to a reproducible environment where I can check what's going on.
