### ISSUE TITLE
Cannot use custom Icons for API level < 23

### ISSUE THREAD

**Issue by jchau207** [cortinico/slidetoact#86]
Android cannot inflate custom icon drawable on API level <23.  

Library Version: 'com.ncorti:slidetoact:0.7.0'
Android Version: 6 (API 23)

stacktrace: 

>  android.view.InflateException: Binary XML file line #210: Binary XML file line #210: Error inflating class com.ncorti.slidetoact.SlideToActView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.bitcoin.mwallet.app.viper.ScreenView.onCreateView(ScreenView.kt:36)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2605)
....
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xhdpi-v4/ic_send.png from xml type xml resource ID #0x7f08018d
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2834)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2789)
        at android.content.res.Resources.getXml(Resources.java:1221)
        at com.ncorti.slidetoact.SlideToActView.parseVectorDrawableCompat(SlideToActView.kt:332)
        at com.ncorti.slidetoact.SlideToActView.<init>(SlideToActView.kt:306)
        at com.ncorti.slidetoact.SlideToActView.<init>(SlideToActView.kt:39)

**Comment by cortinico** [comment]
Hi @jchau207,
Thanks for using the library and reporting this issue,

From what I can see from the stacktrace, you're trying to use a custom icon that is not a vector drawable: `ic_send.png`. Please update this resource to be a vector drawable as well. Using custom icons that are not vector drawables is not supported.

**Comment by cortinico** [comment]
Also see #84 for more context
